services:
  - type: web
    name: Fintrackr-backend
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
